version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules # Do not try to map node_modules inside the container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Do not try to map node_modules inside the container
      - .:/app
    command: ["npm", "run", "test"]